import { Button, ECorpIcon, Grid, TextBox } from "@ecorp/ui-lib";
import type { NextPage } from "next";
import Head from "next/head";
import React from "react";

const Home: NextPage = () => {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Grid gap="10px">
				<TextBox backgroundColor={"navy"} color={"#FFFFFF"}><span>TextBox</span></TextBox>
				<TextBox backgroundColor={"navy"} color={"#FFFFFF"}><span>TextBox</span></TextBox>
				<TextBox backgroundColor={"navy"} color={"#FFFFFF"}><span>TextBox</span></TextBox>
				<TextBox backgroundColor={"navy"} color={"#FFFFFF"}><span>TextBox</span></TextBox>
				<TextBox backgroundColor={"navy"} color={"#FFFFFF"}><span>TextBox</span></TextBox>
				<TextBox backgroundColor={"navy"} color={"#FFFFFF"}><span>TextBox</span></TextBox>
				<TextBox backgroundColor={"navy"} color={"#FFFFFF"}><span>TextBox</span></TextBox>
				<TextBox backgroundColor={"navy"} color={"#FFFFFF"}><span>TextBox</span></TextBox>
				<TextBox backgroundColor={"navy"} color={"#FFFFFF"}><span>TextBox</span></TextBox>
				<TextBox backgroundColor={"navy"} color={"#FFFFFF"}><span>TextBox</span></TextBox>
				<TextBox backgroundColor={"navy"} color={"#FFFFFF"}><span>TextBox</span></TextBox>
			</Grid>
			<Button text="test" icon={ECorpIcon.DRINK} iconPosition="right" />
		</>
	);
};

export default Home;
